import { Container, Heading, Stack, Text } from "@chakra-ui/layout";
import { Input, InputGroup, InputRightAddon } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { BsSearch } from "react-icons/bs";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxW="container.xl" mx="auto" my="2em">
          <Stack
            spacing={4}
            minHeight="80vh"
            alignItems="center"
            justifyContent="center"
          >
            <Heading
              as="h1"
              fontSize={["3xl", "4xl", "6xl"]}
              width={["100%", "90%", "100%"]}
              textAlign="center"
              mx="auto"
            >
              Find out what's happening with government projects in your area
            </Heading>
            <Text
              color="gray.400"
              textAlign="center"
              mx="auto"
              fontSize={["xl", "2xl", "3xl"]}
            >
              Find It. Weigh In. Watch It
            </Text>

            <InputGroup size="lg" width={["100%", "65%", "35%"]} mx="auto">
              <Input
                type="text"
                _focus={{ ring: 0, borderColor: "#3AAFA9" }}
                placeholder="Search by location"
              />
              <InputRightAddon color="#fff" bgColor="#3AAFA9">
                <BsSearch />
              </InputRightAddon>
            </InputGroup>
          </Stack>
        </Container>
      </main>
    </div>
  );
};

export default Home;
